= Project Proposal - LeoTurnier
Lorenz Gahleitner, Jonas Birklbauer, Nico Bojer, Tarik Hosic
1.0.1, 2020-10-11: Some notes
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Project Name
LeoTurnier

=== Client
The project is created for the HTBLA-Leonding.

=== Project Team

|===
|Member |Position

|Gahleitner Lorenz
|Project leader

|Birklbauer Jonas
|Project member

|Bojer Nico
|Project member

|Hosic Tarik
|Project member
|===

=== Project Background
At the moment, the entire planning of the tournament is still done manually,
and it is very tedious to follow and register. It is done with a written
entry on a board, and you can only follow the progress by watching.
"LeoTurnier" should change exactly that.


=== Project Goals
The main goal of this project was to simplify the tournament
administration and make the tournament process of all
tournaments more public and accessible.

=== Project Functions
* Keep track of already played matches
* Compatible for various sports
* Organise upcoming matches
* Display the tournament progress
* Export to .csv and .pdf files
* Notifications via e-mail
* Save all data in a database

=== Project Description
The software helps to organise tournaments. It creates a leaderboard which will display past
matches and upcoming ones. Once a game is about to start an e-mail will be sent to the organiser,
notifying them. Scores will be manually added, automatically displayed and in a database stored.
Additionally, a list of either the upcoming or already played matches can
be exported into a .csv or .pdf file.

=== Milestones
* Code basis of the existing project was taken over and works
* Models fit all tournament modes
* Completeness of the tournament models were checked
* Web interface is implemented
* API for the web interface was created
* Integration of the user interface and API was carried out
* Integration test was carried out
* Deployment was carried out
* Application was installed and tested

=== Stakeholder
Participants of the tournament, organizers and spectators.

=== Project Result
"LeoTurnier" is a tournament management program that manages different types of tournaments
(e.g. individual tournament, team tournament), as well as different types of game systems
(KO system, group system).

=== Project risks
* System architecture, technologies and functional scope not known
* Change javafx to webclient
* Infrastructure and required items not specified
* Complex model for a tournament and evaluation may need to be built
* User group not computer savvy
* Workflow for a tournament not yet clarified/known (group and KO model)
* Rare tournament mode cannot be displayed

=== Project Start
The project was started on 5th October 2020.
