= Project Proposal - LeoTurnier
Nico Bojer
1.0.0, 2020-10-06: Some notes
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Project Name
LeoTurnier

=== Client
The project is created for the HTBLA-Leonding.

=== Project Team
Gahleitner Lorenz (Project leader) +
Birklbauer Jonas +
Bojer Nico +
Hosic Tarik

=== Project Background
"LeoTurnier" is a tournament management program that manages different types of tournaments
(e.g. individual tournament, team tournament), as well as different types of game systems
(KO system, group system).
At the moment the whole tournament planning is still done manually.

=== Project Goals
* Keep track of already played matches.
* Organise upcoming matches
* Display the next upcoming match
* Export to .csv and .pdf files
* Notifications via e-mail
* Save all data in a database

=== Project Description
The software helps to organise tournaments. It creates a leaderboard which will display past
matches and upcoming ones. Once a game is about to start an e-mail will be sent to the organiser,
notifying them. Scores will be manually added, automatically displayed and in a database stored.
Additionally, a list of either the upcoming or already played matches can
be exported into a .csv or .pdf file.

